# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: c0dec0dec0de's code
author:
  name: c0dec0dec0de
  email: "c0dec0dec0de@proton.me"
description: >-
  A sparse tech blog where I intentionally do things the wrong way.
baseurl: ""
url: "https://0xc0dec0dec0de.github.io"

# Build settings
remote_theme: "jekyll/minima"
plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark
  social_links:
    - platform: github
      user_url: "https://github.com/0xc0dec0dec0de"
      title: "0xc0dec0dec0de"
    - platform: mastodon
      user_url: "https://hachyderm.io/@c0dec0dec0de"
      title: "@c0dec0dec0de@hachyderm.io"
    - platform: rss
      user_url: "https://0xc0dec0dec0de.github.io/feed.xml"
      title: "RSS Feed"

exclude:
  - Makefile
  - vendor
  - Gemfile
  - Gemfile.lock
